# go
[[languages]]
name = "go"
auto-format = true
formatter = { command = "goimports" }

# rust
[[language]]
name = "rust"

[language-server.rust-analyzer.config.check]
command = "clippy"

# TypeScript
[[language]]
name = "typescript"
file-types = ["ts", "jsx"]
